# Build examples with Platformio
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# https://docs.platformio.org/en/latest/integration/ci/github-actions.html

name: PlatformIO CI

on:
  push:
    branches: [ master, feat ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.h'
      - '**.c'
      - '**.ini'
      - '**.yml'
  pull_request:
    branches: [ master]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.h'
      - '**.c'
      - '**.ini'
      - '**.yml'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        code:
          - "."

    steps:
      - uses: actions/checkout@v3
      - name: PIO Cache
        id: cache-pio
        uses: actions/cache@v3
        env:
          cache-name: cache-pio-pkgs
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio-${{env.cache-name}}
          restore-keys: |
            ${{ runner.os }}-pio-
            ${{ runner.os }}-
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Platformio
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          #platformio pkg update
      - name: Run PlatformIO
        run: |
          pio run -e espem -e espem_debug
#      env: 
#        PLATFORMIO_CI_SRC: ${{ matrix.code }}
#      run: |
#        pio ci -c ${{ matrix.code }}/platformio.ini